config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home' # OK
  devise_for :users, controllers: { registrations: "registrations" }

  resources :political_parties, only: [ :index, :new, :create, :show ] do
    resources :politician_links, only: [:new, :create, :destroy]
  end

  resources :users, only: :show

  resources :politician_scores, only: [:index]

  resources :leagues, only: [ :new, :create, :index, :show ] do
    resources :league_connections, only: :create
  end

  get '/my_leagues', to: 'leagues#my_leagues'
  get '/politician_scores', to: 'politician_scores#index'
  get '/rage_page', to: 'pages#rage_page'
  get '/instructions', to: 'pages#instructions'

  require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end

end

  # get '/news_items', to: 'news_items#index'
  # get '/search_results', to: 'pages#search_results'
   # resources :league_connections, only: :index
  # resources :politicians, only: [ :index, :show ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/league.rb
class League < ApplicationRecord
  belongs_to :user

  has_many :league_connections
  has_many :political_parties, through: :league_connections

  has_many :user_league_connections
  has_many :users, through: :user_league_connections
  validates :name, presence: true, uniqueness: true

  def creator
    return self.user
  end

  include AlgoliaSearch

  algoliasearch do

  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :find_league, only: [:edit, :update, :show, :destroy]

  def index
    @leagues = policy_scope(League).order(created_at: :desc)
  end

  def new
    @league = League.new
    authorize @league
  end

  def my_leagues
    @leagues = current_user.political_parties.map(&:leagues)
    authorize(@leagues.first)
  end

  def create
    @league = League.new(league_params)
    @league.user = current_user
    authorize @league
    if @league.save
      @league_connection = LeagueConnection.new
      @league_connection.league = @league
      # league_connection.user = current_user
      @league_connection.save
      # LeagueMailer.creation_confirmation(@league).deliver_now
      redirect_to league_path(@league)
    else
     render :new
    end
  end

  def show
  end

  private

  def find_league
   @league = League.find(params[:id])
   authorize @league
  end

  def league_params
    params.require(:league).permit(:name)
  end
end








  # def edit
  #   @politician = Politician.find(params[:politician_id])
  # end



    # def update
  #   if @league.update(league_params)
  #     redirect_to league(@league)
  #   else
  #     render :edit
  #   end
  # end

  # def destroy
  #   @league.destroy
  #   @league = policy_scope(League)
  # end

app/views/leagues/index.html.erb
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item active">
    <a class="nav-link" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">All leagues</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">My leagues</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade active in" id="home" role="tabpanel" aria-labelledby="home-tab">
    <h3 class="league-headers">All leagues</h3>
      <div class="button-padding">
         <%= link_to "Add league", new_league_path, class: 'main-button modal-button'%>
      </div>
        <% @leagues.each do |league| %>
          <%= link_to league_path(league) do %>
            <div>
              <aside class="sidebar-left3">
              </aside>

              <article class="league-box">
                <div class="grid-container">
                  <div>
                    <p class="party-members">
                      <%= league.name %>
                    </p>
                    <p class="party-members-count">
                      Created by <%= league.user.username %>
                    </p>
                  </div>
                  <div>
                    <p class="parties-count">
                      <%= league.political_parties.count %>
                      <% if league.political_parties.count == 1 %>
                        party
                      <% else %>
                        parties
                      <% end %>
                    </p>
                    <p class="score-number">
                    </p>
                  </div>
                </div>
              </article>
           </div>
          <% end %>
        <% end %>
  </div>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
    <h3 class="league-headers">Your leagues</h3>
      <div class="button-padding">
      <%= link_to "Add league", new_league_path, class: 'main-button modal-button'%>
      </div>
      <% current_user.leagues.each do |league| %>
        <%= link_to league_path(league) do %>
      <div>
          <aside class="sidebar-left3">
          </aside>

          <article>
            <div class="grid-container">
              <div>
                <p class="party-members">
                  <%= league.name.upcase %>
                </p>
                <p class="party-members-count">
                  <%= league.political_parties.count %>
                  <% if league.political_parties.count == 1 %>
                    party
                  <% else %>
                    parties
                  <% end %>
                </p>
              </div>
            </div>
          </article>
          <aside class="sidebar-right3">
            <p>
            </p>
          </aside>
      </div>
      <% end %>
      <% end %>
  </div>
</div>

app/views/leagues/my_leagues.html.erb
<% current_user.political_parties.each do |political_party| %>
  <% political_party.leagues.each do |league| %>
    <%= league.name %>
  <% end %>
<% end %>





<% if false %>
  <h2>Leagues my parties belong to</h2>

  <% current_user.leagues.each do |league| %>
    <%= link_to league_path(league) do %>
  <div>
      <aside class="sidebar-left3">
      </aside>

      <article>
        <div class="grid-container">
          <div>
            <p class="party-members">
              <%= league.name.upcase %>
            </p>
            <p class="party-members-count">
              <%= league.political_parties.count %>
              <% if league.political_parties.count == 1 %>
                party
              <% else %>
                parties
              <% end %>
            </p>
          </div>
        </div>
      </article>
      <aside class="sidebar-right3">
        <p>
        </p>
      </aside>
  </div>
  <% end %>
  <% end %>
   <%= link_to "Create your own league", new_league_path, class: 'main-button modal-button'%>
<% end %>

app/views/leagues/new.html.erb
<div class="row homepage-container">
  <div class="col-xs-12 col-sm-4 col-sm-offset-4">
    <h2>Create Your League</h2>

    <%= simple_form_for @league, url: leagues_path do |f| %>
      <%= f.error_notification %>
      <div class="form-inputs">
        <div class="custom-form-group">
          <%= f.input :name,
                      autofocus: true,
                      label: "League's name",
                      label_html: { class: "login-form-label" },
                      input_html: { class: "login-form-input" } %>
        </div>
      </div>
      <div class="form-actions flexbox-column">
        <%= f.button :submit, "Submit", class: "main-button" %>
      </div>
    <% end %>


  </div>
</div>

app/views/leagues/show.html.erb
<h1 class="league-header"><%= @league.name %></h1>
    <!-- Upper container -->
<div class="league-statistics">
  <div class="league-numbers">
    <h4>Members</h4>
    <p><%= @league.political_parties.count %></p>
  </div>
  <% unless @league.political_parties.first.nil? %>
    <div class="league-leader">
        <h4>Founding Party</h4>
        <div class="leader-details">
          <div>
            <p class="party-title"><%= link_to @league.political_parties.first.name, political_party_path(@league.political_parties.first) %></p>
            <p class="league-user"><%= @league.political_parties.first.user.username %></p>
          </div>
          <div class="leader-score">
            <p><%= @league.political_parties.first.score %></p>
          </div>
        </div>
    </div>
  <% end %>
</div>

    <!-- Lower container -->
<% unless @league.political_parties.first.nil? %>
  <h4>Parties</h4>
  <% @league.political_parties.sort_by{|i| -i.score}.each_with_index do |party, index| %>
    <div class="league-parties">
      <div class="league-party-card">
        <div class="party-rank">
          <%= index + 1 %>
        <div class="user-avatar" style="background-image: url(<%= cl_image_path party.user.cl_photo %>);"></div>
        </div>
        <div class="party-name">
          <div>
            <p class="party-title"><%= link_to party.name, political_party_path(party) %></p>
            <p class="league-user"><%= party.user.username %></p>
          </div>
        </div>
        <div class="party-score"><%= party.score %></div>
      </div>
    </div>
  <% end %>
<% end %>
<% unless current_user.political_parties.all? { |party| @league.political_parties.include?(party) } %>
  <h4>Add party to league</h4>
<% end %>
<% current_user.political_parties.each do |political_party| %>
  <% unless @league.political_parties.include? political_party %>
    <%= link_to league_league_connections_path(political_party: political_party, league_id: @league), {method: :post} do %>
      <div class="league-card">
          <%= political_party.name  %>
      </div>
    <% end %>
  <% end %>
<% end %>
</div>