config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home' # OK
  devise_for :users, controllers: { registrations: "registrations" }

  resources :political_parties, only: [ :index, :new, :create, :show ] do
    resources :politician_links, only: [:new, :create, :destroy]
  end

  resources :users, only: :show

  resources :politician_scores, only: [:index]

  resources :leagues, only: [ :new, :create, :index, :show ] do
    resources :league_connections, only: :create
  end

  get '/my_leagues', to: 'leagues#my_leagues'
  get '/politician_scores', to: 'politician_scores#index'
  get '/rage_page', to: 'pages#rage_page'
  get '/instructions', to: 'pages#instructions'

  require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end

end

  # get '/news_items', to: 'news_items#index'
  # get '/search_results', to: 'pages#search_results'
   # resources :league_connections, only: :index
  # resources :politicians, only: [ :index, :show ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/political_party.rb
class PoliticalParty < ApplicationRecord
  belongs_to :user
  has_many :league_connections
  has_many :leagues, through: :league_connections

  has_many :politician_links
  has_many :politicians, through: :politician_links

  include AlgoliaSearch

  algoliasearch do

  end
  # if no photo uploded will display from stock photos
  def cl_photo
      if photo?
        photo
      else
        'https://pbs.twimg.com/profile_images/854676302317703169/RQw2coJC_400x400.jpg'
    end
  end

  def score
    sum = 0
    politicians.each do |p|
      sum += p.score
    end
    return sum
  end
end

app/controllers/political_parties_controller.rb
class PoliticalPartiesController < ApplicationController
  before_action :find_political_party, only: :show

  def index
    @political_parties = policy_scope(PoliticalParty)
  end

  def new
    @political_party = PoliticalParty.new
    @user = current_user
    authorize @political_party
  end

  def show
    @political_party = PoliticalParty.find(params[:id])
     authorize @political_party
  end

  def create
    @political_party = PoliticalParty.new(political_party_params)
    @political_party.user = current_user
    authorize @political_party
    if @political_party.save
      redirect_to new_political_party_politician_link_path(@political_party)
    else
      render :new
    end
  end

  private

  def find_political_party
   @political_party = PoliticalParty.find(params[:id])
   authorize @political_party
  end

  def political_party_params
    params.require(:political_party).permit(:name, :photo)
  end
end

app/controllers/political_party_controller.rb
class PoliticalPartyController < ApplicationController
  def index
    @political_parties = PoliticalParty.all
  end

  def new
    @political_party = PoliticalParty.new
  end

  def create
    @political_party = PoliticalParty.new(political_party_params)
    @political_party.user = current_user
    authorize = @political_party
    if @political_party.save
      redirect_to political_party(@political_party)
    else
      render :new
    end
  end

  def update
    @political_party = PoliticalParty.find(params[:id])
      if @political_party.update(political_party_params)
      redirect_to political_party(@political_party)
    else
      render :edit
  end

  def destroy
    @political_party.destroy
  end

  private

  def political_party_params
    params.require(:political_party).permit(:name)
  end
end

app/views/political_parties/_form.html.erb
<%= simple_form_for political_party do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <div class="custom-form-group">
      <%= f.input :name,
                   required: true,
                   autofocus: true,
                   label: "Name",
                   label_html: { class: "login-form-label" },
                   input_html: { autocomplete: "username", class: "login-form-input" } %>
    </div>
  </div>
  <div class="form-actions flexbox-column">
    <%= f.button :submit, "Submit", class: "main-button" %>
  </div>
<% end %>

app/views/political_parties/index.html.erb
<h2>My politicial parties</h2>

<div class="button-padding">
  <%= link_to "Add party", new_political_party_path, class: 'main-button modal-button'%>
  </div>
<% current_user.political_parties.each do |party| %>
  <%= link_to political_party_path(party) do %>
<div>
    <aside class="sidebar-left3">
    </aside>

    <article>
      <div class="grid-container">
        <div>
          <p class="party-members">
            <%= party.name.upcase %>
          </p>
          <p class="party-members-count">
            <%= party.politicians.count %>
            party members
          </p>
        </div>
        <div>
          <p class="score">
            SCORE
          </p>
          <p class="score-number">
            <%= party.score %>
          </p>
        </div>
      </div>
    </article>
    <aside class="sidebar-right3">
      <p>
      </p>
    </aside>
</div>
<% end %>
<% end %>

app/views/political_parties/new.html.erb
<div class="row homepage-container">
  <div class="col-xs-12 col-sm-4 col-sm-offset-4">
    <h2>Create Your Party</h2>
    <%= render 'form', political_party: @political_party %>
  </div>
</div>

app/views/political_parties/show.html.erb
<h1 class="party-header"><%= @political_party.name %></h1>
    <!-- Upper container -->
    <div class="party-statistics">
      <div class="party-numbers">
        <h4>Score</h4>
        <p><%= @political_party.score %></p>
      </div>
      <div class="party-numbers">
        <h4>Members</h4>
        <p><%= @political_party.politicians.count %></p>
      </div>
      <div class="party-leagues">
        <h4>Leagues</h4>

            <% if @political_party.leagues == [] %>
              <p>No leagues yet</p>
            <div class="button-flex">
              <%= link_to "Create a league", new_league_path, class: "main-button party-league-button" %>
              <%= link_to "Join a league", leagues_path, class: "main-button party-league-button" %>
            </div>
            <% else %>
            <ul>
              <% @political_party.leagues.each do |league| %>
                <li><%= link_to league.name, league_path(league) %></li>
              <% end %>
            </ul>
          <% end %>
      </div>
    </div>

    <!-- Lower container -->
    <h4>Politicians</h4>
    <% if current_user.political_parties.include? @political_party %>
      <%= link_to "Edit", new_political_party_politician_link_path(@political_party) %>
    <% end %>
    <% @political_party.politicians.sort_by{|i| -i.score}.each_with_index do |politician, index| %>
      <div class="party-politicians">
        <div class="party-politician-card">
          <div class="politician-rank">
            <%= index + 1 %>
          <div class="politician-avatar" style="background-image: url(<%= cl_image_path politician.photo %>);"></div>
          </div>
          <div class="politician-name"><%= politician.name %></div>
          <div class="politician-score"><%= politician.score %></div>
        </div>
      </div>
    <% end %>