config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home' # OK
  devise_for :users, controllers: { registrations: "registrations" }

  resources :political_parties, only: [ :index, :new, :create, :show ] do
    resources :politician_links, only: [:new, :create, :destroy]
  end

  resources :users, only: :show

  resources :politician_scores, only: [:index]

  resources :leagues, only: [ :new, :create, :index, :show ] do
    resources :league_connections, only: :create
  end

  get '/my_leagues', to: 'leagues#my_leagues'
  get '/politician_scores', to: 'politician_scores#index'
  get '/rage_page', to: 'pages#rage_page'
  get '/instructions', to: 'pages#instructions'

  require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end

end

  # get '/news_items', to: 'news_items#index'
  # get '/search_results', to: 'pages#search_results'
   # resources :league_connections, only: :index
  # resources :politicians, only: [ :index, :show ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>

  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>


<script>

</script>

app/views/shared/_navbar.html.erb
<div class="navbar-fixed-top">

  <div class="navbar-wagon">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "squarewhite.png", height: 50 %>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <% if user_signed_in? %>

        <!-- Links when logged in -->
        <% if current_user.political_parties.any? %>
          <%= link_to 'My Parties', political_parties_path, class: "navbar-wagon-item navbar-wagon-link #{'active' if params[:controller] == 'political_parties'}" %>
        <% else %>
          <%= link_to 'Create my party', new_political_party_path, class: "navbar-wagon-item navbar-wagon-link #{'active' if params[:controller] == 'political_parties'}" %>
        <% end %>

        <%= link_to 'Leagues', leagues_path, class: "navbar-wagon-item navbar-wagon-link #{'active' if params[:controller] == 'leagues'}" %>

        <%= link_to "Politicians' Scores", politician_scores_path, class: "navbar-wagon-item navbar-wagon-link #{'active' if params[:controller] == 'politician_scores'}" %>

        <%= link_to 'Rage Page', rage_page_path, class: "navbar-wagon-item navbar-wagon-link #{'active' if params[:action] == 'rage_page'}" %>

        <!-- Avatar with dropdown menu -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%#= image_tag current_user.cl_photo , class: "avatar dropdown-toggle", id: "navbar-wagon-menu", data: { toggle: "dropdown" } %>
            <div class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown" style="background-image: url( <%= image_path current_user.cl_photo%> );"></div>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to user_path(current_user) do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to instructions_path do %>
                  <i class="fas fa-dice-three"></i><%= t(".profile", default: " Rules") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: '#' do %>
                 <i class="fas fa-sign-out-alt"></i><%= t(".sign_out", default: " Log out") %>
                <% end %>

              </li>
            </ul>
          </div>
        </div>


      <% else %>
        <!-- Login link (when logged out) -->
        <button class="main-button" id="login-button" data-toggle="modal" data-target="#myModal2">Log In</button>
      <% end %>
    </div>


    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <% if user_signed_in? %>
            <% if current_user.political_parties.any? %>
             <li><%= link_to 'My Parties', political_parties_path %></li>
            <% else %>
              <li><%= link_to 'Create my party', new_political_party_path %></li>
            <% end %>
             <li> <%= link_to "Leagues", leagues_path(current_user.leagues) %></li>
            <li>
              <%= link_to "Politicians' Scores", politician_scores_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
            <li>
              <%= link_to 'Rage Page', rage_page_path, class: "navbar-wagon-item navbar-wagon-link #{'active' if params[:action] == 'rage_page'}" %>
            </li>
            <li>
              <%= link_to instructions_path do %>
                <i class="fas fa-dice-three"></i><%= t(".profile", default: " Rules") %>
              <% end %>
            </li>
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li><%= link_to destroy_user_session_path, method: :delete, class: '#' do %>
              <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: " Log out") %>
            <% end %>
            </li>

          <% else %>
            <li>
              <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path %>Link tag</li>
            <li>
              <%= link_to t(".sign_in", default: "Login"), new_user_session_path %> Link tag
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered my-modal-dialog" role="document">
    <div class="modal-content my-modal2-content">
      <div class="modal-body my-modal-body">
        <h3 class="modal-title my-modal-title" id="exampleModalLongTitle">Log In</h3>
        <button type="button" class="close cross" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= simple_form_for(:user, as: :user, url: session_path(:user)) do |f| %>

        <div class="form-inputs modal-form-inputs">
          <div class="custom-form-group modal-custom-form-group">
            <%= f.input :email,
                               required: true,
                               autofocus: true,
                               label: "Email",
                               label_html: { class: "login-form-label" },
                               input_html: { autocomplete: "email", class: "login-form-input" } %>
          </div>
          <div class="custom-form-group modal-custom-form-group">
            <%= f.input :password,
                        required: true,
                        hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                        label: "Password",
                        label_html: { class: "login-form-label" },
                        input_html: { autocomplete: "new-password", class: "login-form-input"  } %>
          </div>
        <div class="form-actions flexbox-column">
          <%= f.button :submit, "Go", class: "main-button modal-button" %>
        </div>
        </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

<%= content_for :after_js do %>
  <script>
    $('#myModal2').on('shown.bs.modal', function () {
      $('#myInput').trigger('focus')
    })
  </script>
<% end %>

app/views/shared/_searchbar.html.erb
<!-- <head>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/instantsearch.js@2.3/dist/instantsearch.min.css">
</head>
<div id="searchbox"><input id="search-input" placeholder="search here"></div>
<div id="hits"></div>
<div id="pagination"></div>

<script type="text/html" id="hit-template">
    <div class="hit">
      <p class="hit-name">{{{_highlightResult.first_name.value}}} {{{_highlightResult.last_name.value}}}</p>
    </div>
  </script>
  <script src="https://cdn.jsdelivr.net/npm/instantsearch.js@2.3/dist/instantsearch.min.js"></script>
  <script src="app.js"></script> -->

<form action="/search_results" method="get">
  <input type="text" name="query" placeholder="Search here">
  <input type="submit" value="Search">
</form>

app/views/shared/_tabs.html.erb
<!-- Bootstrap tabs -->