config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home' # OK
  devise_for :users, controllers: { registrations: "registrations" }

  resources :political_parties, only: [ :index, :new, :create, :show ] do
    resources :politician_links, only: [:new, :create, :destroy]
  end

  resources :users, only: :show

  resources :politician_scores, only: [:index]

  resources :leagues, only: [ :new, :create, :index, :show ] do
    resources :league_connections, only: :create
  end

  get '/my_leagues', to: 'leagues#my_leagues'
  get '/politician_scores', to: 'politician_scores#index'
  get '/rage_page', to: 'pages#rage_page'
  get '/instructions', to: 'pages#instructions'

  require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end

end

  # get '/news_items', to: 'news_items#index'
  # get '/search_results', to: 'pages#search_results'
   # resources :league_connections, only: :index
  # resources :politicians, only: [ :index, :show ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/politician_link.rb
class PoliticianLink < ApplicationRecord
  belongs_to :politician
  belongs_to :political_party
end

app/controllers/politician_links_controller.rb
class PoliticianLinksController < ApplicationController
  def new
    @politician_link = PoliticianLink.new
    if params[:query].blank?
      @politicians = Politician.all
    else
      @politicians = Politician.search_politicians(params[:query])
    end
    @political_party = PoliticalParty.find(params[:political_party_id])
    @num_of_politicians = @political_party.politicians.count
    authorize @politician_link
  end

  def create
    @politician_id = params[:politician_link][:politician_id]
    @politician = Politician.find(@politician_id.to_i)

    @political_party = PoliticalParty.find(params[:political_party_id])
    @politician_link = PoliticianLink.new(politician_link_params)
    authorize @politician_link
    @num_of_politicians = @political_party.politicians.count
    if @politician_link.save
      # redirect_to new_political_party_politician_link_path(@political_party)
      respond_to do |format|
        format.html
        format.js
      end
    else
      render :new
    end
  end

  def destroy
    @politician_id = params[:politician]
    @politician = Politician.find(@politician_id.to_i)

    @political_party = PoliticalParty.find(params[:political_party_id])
    @politician_link = PoliticianLink.find(params[:id])

    authorize @politician_link
    @politician_link.destroy
    # redirect_to new_political_party_politician_link_path(@political_party)
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def politician_link_params
    params.require(:politician_link).permit(:politician_id, :political_party_id)
  end
end

app/views/politician_links/_politician.html.erb
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="card-container ">
            <div class="card card<%=politician.id%>">
              <% if politician.party == "Labour" %>
                <div class="front" style="background-color: #d14253">
              <% elsif politician.party == "Conservative" %>
                <div class="front" style="background-color: #3c508c">
              <% elsif politician.party == "Lib Dem" %>
                <div class="front" style="background-color: #ef9240">
              <% elsif politician.party == "SNP" %>
                <div class="front" style="background-color: #f2f274">
              <% elsif politician.party == "UKIP" %>
                <div class="front" style="background-color: #88498f">
              <% elsif politician.party == "Green" %>
                <div class="front" style="background-color: #5db166">
              <% else %>
                <div class="front" style="background-color: #949396">
              <% end %>
                  <% politician.cl_photo %>

                  <div class="politician-image" style="background-image: linear-gradient(180deg, rgba(0,0,0,0.1) 0%, rgba(0,0,0,0.1) 90%), url(<%= cl_image_path politician.cl_photo %>);"></div>
                  <% if politician.party == "SNP" %>
                    <h2 class="first snp"><%= politician.first_name %></h2>
                    <h2 class="last snp"><%= politician.last_name %></h2>
                  <% else %>
                    <h2 class="first"><%= politician.first_name %></h2>
                    <h2 class="last"><%= politician.last_name %></h2>
                  <% end %>
                  <% pl = @political_party.politician_links.find {|pl| pl.politician_id == politician.id} %>
                  <%# if @current_user.political_parties.last.politicians.include? politician %>
                  <% if @political_party.politicians.include? politician %>
                    <%= link_to political_party_politician_link_path(@political_party, pl, politician: politician), method: :delete, remote: true do %>
                      <i class="fas fa-minus minus"></i>
                    <% end %>
                  <% else %>
                    <%= link_to(political_party_politician_links_path(@political_party, politician_link: {politician_id: politician.id, political_party_id: @political_party.id}), method: :post, remote: true) do %>
                      <% if politician.party == "Green" %>
                        <i class="fas fa-plus add" id="caroline-add"></i>
                      <% else %>
                        <i class="fas fa-plus add"></i>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
                <div class="back">
                  <h2>About</h2>
                  <p>
                    <%= politician.about %>
                  </p>
                </div>
            </div>
          </div>
        </div>

app/views/politician_links/create.js.erb
document.getElementById("politician<%= @politician_id %>").innerHTML = "<%= j render 'politician.html.erb', politician: @politician, political_party: @political_party %>"

$('.politician-image').on('click', function (event) {
  console.log(event.currentTarget)
  let className = event.currentTarget.parentNode.parentNode.className.split(" ")[1]
  $(`.${className}`).toggleClass('flipped');
});

$('.back').on('click', function (event) {
  console.log(event.currentTarget.parentNode)
  let className = event.currentTarget.parentNode.className.split(" ")[1]
  $(`.${className}`).toggleClass('flipped');
});

document.querySelector(".party-full-banner").dataset.ben = `<%= @num_of_politicians %>`



if (document.querySelector(".party-full-banner").dataset.ben >= 7) {
  document.querySelector(".party-full-banner").style.display = "block";
} else {
  document.querySelector(".party-full-banner").style.display = "none";
}

app/views/politician_links/destroy.js.erb
document.getElementById("politician<%= @politician_id %>").innerHTML = "<%= j render 'politician.html.erb', politician: @politician, political_party: @political_party %>"

$('.politician-image').on('click', function (event) {
  console.log(event.currentTarget)
  let className = event.currentTarget.parentNode.parentNode.className.split(" ")[1]
  $(`.${className}`).toggleClass('flipped');
});

$('.back').on('click', function (event) {
  console.log(event.currentTarget.parentNode)
  let className = event.currentTarget.parentNode.className.split(" ")[1]
  $(`.${className}`).toggleClass('flipped');
});

document.querySelector(".party-full-banner").dataset.ben = `<%= @num_of_politicians %>`



if (document.querySelector(".party-full-banner").dataset.ben >= 7) {
  document.querySelector(".party-full-banner").style.display = "block";
} else {
  document.querySelector(".party-full-banner").style.display = "none";
}

app/views/politician_links/new.html.erb
<div class="cards-body">
  <div class="row">
    <h2 class="new-party-header">Choose your members for  <%= link_to @political_party.name, political_party_path(@political_party) %></h2>
    <div class="info-button">
      <button type="button" class="main-button home-button" id="info-button-new" data-toggle="modal" data-target="#myModalRules">Info</button>
    </div>
    <%= form_tag new_political_party_politician_link_path(@political_party), :id => 'search-bar', method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search for a politician"
      %>
    <% end %>
    <div class="party-full-banner" data-ben="<%= @num_of_politicians %>" style="<%= @num_of_politicians >= 8 ? 'display: block;' : 'display: none;' %>">
      <%= link_to political_party_path(@political_party) do %>
        <div class="alert-party">
          <p>Your Party is Full! Click to view your party <%= @political_party.name %></p>
        </div>
      <% end %>
    </div>

    <% @politicians.each do |politician| %>
      <div id="politician<%=politician.id %>">
        <%= render "politician.html.erb", politician: politician %>
      </div>
    <% end %>
  </div>
</div>


<div class="modal fade" id="myModalRules" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered my-modal-dialog" role="document">
    <div class="modal-content my-rules-modal-content">
      <div class="modal-body my-modal-body">
        <h3 class="modal-title my-modal-title" id="exampleModalLongTitle">Info</h3>
        <button type="button" class="close cross" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <div class="modal-parties">
          <div class="modal-party">
            <p>Labour</p>
            <i class="fas fa-square labour"></i>
          </div>
          <div class="modal-party">
            <p>Conservative</p>
            <i class="fas fa-square conservative"></i>
          </div>
          <div class="modal-party">
            <p>Liberal Democrats</p>
            <i class="fas fa-square lib-dem"></i>
          </div>
          <div class="modal-party">
            <p>SNP</p>
            <i class="fas fa-square snp"></i>
          </div>
          <div class="modal-party">
            <p>Green</p>
            <i class="fas fa-square greens"></i>
          </div>
          <div class="modal-party">
            <p>UKIP</p>
            <i class="fas fa-square ukip"></i>
          </div>
        </div>
        <div class="modal-rules">
          <p>Politicians' scores are calculated based on their <strong class="modal-bold">role in parliament</strong> and the number of times they're <strong class="modal-bold">mentioned in the news</strong> each day, going on the basis that all news is good news.</p>
        </div>
        <a href="http://www.fantasy-politics.xyz/instructions" id="modal-rules-button" class="main-button modal-button" target="_blank">Full Rules</a>
      </div>
    </div>
  </div>
</div>

<%= content_for :after_js do %>
  <script>
    $('#myModalRules').on('shown.bs.modal', function () {
      $('#myInput').trigger('focus')
    })
  </script>
<% end %>